version: '3.4'

services:
  w-chatbot-ui:
    container_name: w-chatbot-ui
    image: europe-west3-docker.pkg.dev/w-calderone/w-chatbot-ui/w-chatbot-ui:latest
    ports:
      - '3000'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.w-chatbot-ui.rule=Host(`gpt.webranking.tools`)'
      - 'traefik.http.routers.w-chatbot-ui.entrypoints=websecure'
      - 'traefik.http.routers.w-chatbot-ui.tls.certresolver=myhttpchallenge'
      - 'traefik.port=3000'
    env_file: .env.production
    networks:
      - chatbot-network
    volumes:
      - ./creds:/app/creds

  traefik:
    image: 'traefik:v2.0.0-rc3'
    container_name: 'traefik'
    command:
      #- "--log.level=DEBUG"
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true'
      - '--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web'
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - '--certificatesresolvers.myhttpchallenge.acme.email=sistemi@webranking.it'
      - '--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json'
    ports:
      - '80:80'
      - '443:443'
      - '8888:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - chatbot-network

networks:
  chatbot-network:
    external: true
