services:
  # ollama:
  #   volumes:
  #     - ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: unless-stopped
  #   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      # args:
      #   OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    # image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui-data:/app/backend/data
      # - ./backend/open_webui:/app/backend/open_webui  # TEMP: for python debug
    # depends_on:
    #   - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      # - 'OLLAMA_BASE_URL=http://ollama:11434'
      - ENABLE_OAUTH_SIGNUP=True
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=True
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - 'WEBUI_SECRET_KEY='
      - OPENAI_API_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  #open-webui: {}